# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be99ce3b4ce7e5070f6674addb43aaab99e7bc1d4120e3a6304a717b06b68c692ea92318bdb187c9b6c86f41914ad6ee2f5d4f66289ca4a4ee138f947a41f18b

test:
  secret_key_base: d48c4e89582a211a93b62ae13d3730b894460ded8e0b52c2c307d5f85798e2417df137bb6abf289eae82954945751226725ea9d1fce86dac3a0cf31129b1d5b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
